# Generated by Django 3.1.7 on 2021-02-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210224_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy_drink',
            name='allergy_drink',
        ),
        migrations.RemoveField(
            model_name='allergy_drink',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='category',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='drink',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='Allergy_drink',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
